#!/bin/sh

SVNSRC="https://source.sakaiproject.org/contrib/"
#SVNSRC="file:/home/dhorwitz/svn"

echo "$SVNSRC"

MYPATH=`pwd`
USER=$MYPATH/users.txt
CONFIG=$MYPATH/config
UCTREPOS=$MYPATH/repos
UCTSVN=$MYPATH/svn


rm -rf $UCTREPOS
mkdir $UCTREPOS


cd  $UCTREPOS

echo "repros: $UCTREPOS "
echo "svn: $UCTSVN"
echo "pwd: `pwd`"

for i in `tr ' ' '_' <$UCTSVN`
#for i in `tr ' ' '_' </home/dhorwitz/tmp/uct/svn`
do
 if [ "$i" ] && [ ${i:0:1} != '#' ]
	then
    echo $i
  
  
     SAKAI=$SVNSRC/$i
     echo "srv: $SAKAI"
     git init $i
     cd $i
  #git 
  #git svn clone $SAKAI --authors-file=$USER --no-metadata -s $i
  
  #https://github.com/nirvdrum/svn2git#readme
     svn2git --revision 55000:HEAD  --nobranches --notags --authors $USER $SAKAI
     #--rootistrunk 
    if [ "$?" != "0" ]
		    then
		    	echo "s"
		  	   exit
		    else 
		       echo "[done]"
		fi
  
  	echo
  
  	echo "git: $i"
  #.git* 
  	echo $CONFIG
  	cp $CONFIG/.gitattributes .
  	cp $CONFIG/.gitignore .
  	cp $CONFIG/LICENSE .
  	git add .gitattributes .gitignore LICENSE
  	git commit -m "NOJIRA .gitattributes .gitignore LICENSE"
  
  	cd ..
  	echo
  	echo
  		else
			echo "[info] $i"
		  	
		fi
done
