#!/bin/sh

SVNSRC="https://source.sakaiproject.org/contrib/programmerscafe"
REPOS="blogwow"
echo "$SVNSRC"

CONFIG=`pwd`
USER=$CONFIG/users.txt
echo $USER
cd ~/tmp/uct/repos 

echo "repros: ~/tmp/uct/repos "

#for i in `tr ' ' '_' < /home/dhorwitz/tmp/uct/svn`
#do
 
  
  echo $REPOS
  
  
  SAKAI=$SVNSRC/$REPOS
  echo "srv: $SAKAI"
  git init $REPOS
  cd $REPOS
  echo `ls `
  
  #git 
  #git svn clone $SAKAI --authors-file=$USER --no-metadata -s $REPOS
  
  #https://github.com/nirvdrum/svn2git#readme
   svn2git --authors $USER $SAKAI
  
  
  echo
  
  echo "git: $REPOS"
  #.git* 
  echo $CONFIG/config
  cp $CONFIG/config/.gitattributes .
  cp $CONFIG/config/.gitignore .
  cp $CONFIG/config/LICENSE .
  git add .gitattributes .gitignore LICENSE
  git commit -m "NOIJIRA .gitattributes .gitignore LICENSE"
  
  cd ..
  echo
  echo
  
#done
